### ISSUE TITLE
Issue pasting a path to a .bat file that contains spaces

### ISSUE THREAD

**Issue by alastairUK** [JanDeDobbeleer/oh-my-posh#2419]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I am attempting to paste 

"c:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvarsall.bat" x64

To setup my compiler

If I use a standard cmd Windows terminal everything is as expected

![image](https://user-images.githubusercontent.com/5337814/174347976-9a44dc4a-f24f-434e-ab0e-1ce4f09236a8.png)

But if I have an oh-my-posh enabled terminal (using cmder) things go wrong

![image](https://user-images.githubusercontent.com/5337814/174348207-c44238f2-ad53-4a49-9a3a-52a359abe399.png)

### Theme

No theme just this lua script

load(io.popen("C:\\Users\\Alastair\\AppData\\Local\\Programs\\oh-my-posh\\bin\\oh-my-posh.exe init cmd"):read("*a"))()

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

other (please specify)

### Log output

```Shell
 alastair   repos    oh-my-posh debug                                                        in cmd at 18:25:46

Version: 8.5.0

Segments:

ConsoleTitle(false) -   0 ms -
session(true)  -   0 ms -  alastair@DESKTOP-17SHRDE 
path(true)     -   0 ms -  repos
shell(true)    -   0 ms -  WindowsTerminal
text(true)     -   0 ms -  no config
exit(true)     -   1 ms -   

Run duration: 37.9913ms

Cache path: C:\Users\alastair\AppData\Local\oh-my-posh

Config path: c:\Users\alastair\Source\repos\"C:\Users\alastair\AppData\Local\oh-my-posh\config.omp.json"

Logs:

2022/06/17 18:25:47 debug: Getenv
C:\Users\alastair\AppData\Local
2022/06/17 18:25:47 Getenv duration: 0s, args: LOCALAPPDATA
2022/06/17 18:25:47 CachePath duration: 0s, args:
2022/06/17 18:25:47 debug: Getenv
"C:\Users\alastair\AppData\Local\oh-my-posh\config.omp.json"
2022/06/17 18:25:47 Getenv duration: 0s, args: POSH_THEME
2022/06/17 18:25:47 Shell duration: 34.7071ms, args:
2022/06/17 18:25:47 resolveConfigPath duration: 34.7071ms, args:
2022/06/17 18:25:47 Init duration: 34.7071ms, args:
2022/06/17 18:25:47 Flags duration: 0s, args:
2022/06/17 18:25:47 config.loadConfig duration: 0s, args:
2022/06/17 18:25:47 Flags duration: 0s, args:
2022/06/17 18:25:47 debug: Getenv

2022/06/17 18:25:47 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/06/17 18:25:47 WindowsRegistryKeyValue duration: 0s, args: HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 debug: WindowsRegistryKeyValue
ColorizationColor(DWORD): 0xC40078D7
2022/06/17 18:25:47 Root duration: 0s, args:
2022/06/17 18:25:47 Shell duration: 0s, args:
2022/06/17 18:25:47 ErrorCode duration: 0s, args:
2022/06/17 18:25:47 IsWsl duration: 0s, args:
2022/06/17 18:25:47 debug: Pwd
C:\Users\alastair\Source\repos
2022/06/17 18:25:47 Pwd duration: 0s, args:
2022/06/17 18:25:47 debug: Home
C:\Users\alastair
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 debug: User
alastair
2022/06/17 18:25:47 User duration: 0s, args:
2022/06/17 18:25:47 debug: Host
DESKTOP-17SHRDE
2022/06/17 18:25:47 Host duration: 0s, args:
2022/06/17 18:25:47 GOOS duration: 0s, args:
2022/06/17 18:25:47 TemplateCache duration: 0s, args:
2022/06/17 18:25:47 Flags duration: 0s, args:
2022/06/17 18:25:47 debug: Pwd
C:\Users\alastair\Source\repos
2022/06/17 18:25:47 Pwd duration: 0s, args:
2022/06/17 18:25:47 debug: Home
C:\Users\alastair
2022/06/17 18:25:47 GOOS duration: 0s, args:
2022/06/17 18:25:47 debug: Getenv

2022/06/17 18:25:47 Getenv duration: 0s, args: SSH_CONNECTION
2022/06/17 18:25:47 debug: Getenv

2022/06/17 18:25:47 Getenv duration: 0s, args: SSH_CLIENT
2022/06/17 18:25:47 TemplateCache duration: 0s, args:
2022/06/17 18:25:47 TemplateCache duration: 0s, args:
2022/06/17 18:25:47 Shell duration: 0s, args:
2022/06/17 18:25:47 debug: Pwd
C:\Users\alastair\Source\repos
2022/06/17 18:25:47 Pwd duration: 0s, args:
2022/06/17 18:25:47 debug: Home
C:\Users\alastair
2022/06/17 18:25:47 GOOS duration: 0s, args:
2022/06/17 18:25:47 debug: Pwd
C:\Users\alastair\Source\repos
2022/06/17 18:25:47 Pwd duration: 0s, args:
2022/06/17 18:25:47 Flags duration: 0s, args:
2022/06/17 18:25:47 debug: Pwd
C:\Users\alastair\Source\repos
2022/06/17 18:25:47 Pwd duration: 0s, args:
2022/06/17 18:25:47 debug: Home
C:\Users\alastair
2022/06/17 18:25:47 GOOS duration: 0s, args:
2022/06/17 18:25:47 GOOS duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 PathSeparator duration: 0s, args:
2022/06/17 18:25:47 GOOS duration: 0s, args:
2022/06/17 18:25:47 IsWsl duration: 0s, args:
2022/06/17 18:25:47 StackCount duration: 0s, args:
2022/06/17 18:25:47 DirIsWritable duration: 0s, args:
2022/06/17 18:25:47 TemplateCache duration: 0s, args:
2022/06/17 18:25:47 TemplateCache duration: 0s, args:
2022/06/17 18:25:47 Shell duration: 0s, args:
2022/06/17 18:25:47 debug: Pwd
C:\Users\alastair\Source\repos
2022/06/17 18:25:47 Pwd duration: 0s, args:
2022/06/17 18:25:47 debug: Home
C:\Users\alastair
2022/06/17 18:25:47 GOOS duration: 0s, args:
2022/06/17 18:25:47 Shell duration: 0s, args:
2022/06/17 18:25:47 Flags duration: 0s, args:
2022/06/17 18:25:47 TemplateCache duration: 0s, args:
2022/06/17 18:25:47 TemplateCache duration: 0s, args:
2022/06/17 18:25:47 Shell duration: 0s, args:
2022/06/17 18:25:47 debug: Pwd
C:\Users\alastair\Source\repos
2022/06/17 18:25:47 Pwd duration: 0s, args:
2022/06/17 18:25:47 debug: Home
C:\Users\alastair
2022/06/17 18:25:47 GOOS duration: 0s, args:
2022/06/17 18:25:47 TemplateCache duration: 0s, args:
2022/06/17 18:25:47 TemplateCache duration: 0s, args:
2022/06/17 18:25:47 Shell duration: 0s, args:
2022/06/17 18:25:47 debug: Pwd
C:\Users\alastair\Source\repos
2022/06/17 18:25:47 Pwd duration: 0s, args:
2022/06/17 18:25:47 debug: Home
C:\Users\alastair
2022/06/17 18:25:47 GOOS duration: 0s, args:
2022/06/17 18:25:47 ErrorCode duration: 0s, args:
2022/06/17 18:25:47 TemplateCache duration: 0s, args:
2022/06/17 18:25:47 TemplateCache duration: 0s, args:
2022/06/17 18:25:47 Shell duration: 0s, args:
2022/06/17 18:25:47 TemplateCache duration: 0s, args:
2022/06/17 18:25:47 debug: Getenv
C:\Users\alastair\AppData\Local
2022/06/17 18:25:47 Getenv duration: 0s, args: LOCALAPPDATA
2022/06/17 18:25:47 CachePath duration: 0s, args:
2022/06/17 18:25:47 Flags duration: 0s, args:
```

**Comment by lewis-yeung** [comment]
This has been fixed in the latest release (v8.5.2). Just update and try again. :)

**Comment by JanDeDobbeleer** [comment]
@alastairUK can you update and try again? We just fixed an issue with `"` for CMD and this could be related.

**Comment by alastairUK** [comment]
Looks like it's still an issue...

![image](https://user-images.githubusercontent.com/5337814/174434738-8cb51bba-9cc5-4204-9fa4-e849377c9d1f.png)

![image](https://user-images.githubusercontent.com/5337814/174434765-79a27e3b-2d88-4ecd-b825-06d8e24eaf0a.png)

**Comment by lewis-yeung** [comment]
@alastairUK Cannot reproduce this in v8.5.2.

![normal](https://user-images.githubusercontent.com/83903009/174436120-67ba485d-55e2-433f-b543-71039bf2b18c.gif)

Are you sure that the ACTUALLY called executable is one of v8.5.2? Please check the following:

- Does `C:\Users\Alastair\AppData\Local\Programs\oh-my-posh\bin\oh-my-posh.exe --version` output `8.5.2`?
- Does `where oh-my-posh` output `C:\Users\Alastair\AppData\Local\Programs\oh-my-posh\bin\oh-my-posh.exe`?

**Comment by alastairUK** [comment]
Hmmm 

![image](https://user-images.githubusercontent.com/5337814/174436617-b4682f63-ff66-4803-91fb-dfda63b10b6e.png)

I use chocolatey to install. Luckily I still have terminal open

![image](https://user-images.githubusercontent.com/5337814/174436698-cbdf4189-0853-4fc7-954b-e9bee034b7aa.png)

![image](https://user-images.githubusercontent.com/5337814/174436714-405e3ad4-3e3a-4bde-b3e9-dadbe4050846.png)

Looks like 8.5.2 changed the install location (which obviously I didn't notice)

**Comment by lewis-yeung** [comment]
> Looks like 8.5.2 changed the install location (which obviously I didn't notice)

@alastairUK OMP itself does not change this. The Chocolatey package is not maintained by this repo.

**Comment by alastairUK** [comment]
All works fine now i'm using 8.5.2.

Thanks!
