### ISSUE TITLE
Unknown character 퀍 appear

### ISSUE THREAD

**Issue by elsennov** [JanDeDobbeleer/oh-my-posh#418]
Hi team, I am using V3. Currently, if the command is error there is this character showing 퀍
I am using windows terminal and use MesloLGM Nerd Font Mono for the font. Do you have any idea why it happened? Thank you.

![image](https://user-images.githubusercontent.com/7565601/106841578-fd145480-66d4-11eb-9523-d4247d279c55.png)

**Comment by itsthekeming** [comment]
I'm also having this issue. I installed oh-my-posh and changed my font to Meslo LGM Nerd Font (not the mono variant) via `settings.json`. I'm using the robbyrussel theme.

I fixed it by exporting the theme and removing the exit code prefix, which contained the glyph in question.

**Comment by JayDouglass** [comment]
I'm using Cascadia Code PL and I'm still getting a unicode blank with the latest commit (0ec90a1). I copy and pasted the glyph from [the ohmyzsh robby russel theme](https://github.com/ohmyzsh/ohmyzsh/blob/master/themes/robbyrussell.zsh-theme): 
`"prefix": "\u2717",`, which fixed the issue.

**Comment by JanDeDobbeleer** [comment]
@JayDouglass it also depends on the font indeed. Feel free to create a PR with that fix (even if small).
