### ISSUE TITLE
session segment always shows username

### ISSUE THREAD

**Issue by jetersen** [JanDeDobbeleer/oh-my-posh#453]
😆 Logic bug, so #448 broke the current behavior as it returns too early and is always enabled.
Since `getUsername` always returns the username so the segmentTemplate is always greater than 0.

I tried fixing the code to have `segmentTemplate` as in have `getUsername` should return `""`\
when `showDefaultUser == false && defaultUserName == username`.

Sadly that breaks a lot of tests 😅

So the enabled would look something like this.
```go
	if segmentTemplate != "" {
		s.Root = s.env.isRunningAsRoot()
		template := &textTemplate{
			Template: segmentTemplate,
			Context:  s,
		}
		s.templateText = template.render()
		return len(s.templateText) > 0
	}
	return false
```

Not sure where the logic for `showDefaultUser` should be located as in you would want to show host or session host depending on other logic. 😓

_Originally posted by @jetersen in https://github.com/JanDeDobbeleer/oh-my-posh/pull/448#r582554002_

**Comment by JanDeDobbeleer** [comment]
@jetersen that does imply you have a template for that segment, right? As the test should catch that use case. Can you share your configuration for `session`?

**Comment by jetersen** [comment]
Sure thing, here you go 😄

https://github.com/jetersen/dotfiles/blob/77294b117b4fa7345ed9a6f1a3bd05a9e4c5116b/oh-my-posh/jetersen.omp.json#L14-L29
https://github.com/jetersen/dotfiles/blob/77294b117b4fa7345ed9a6f1a3bd05a9e4c5116b/powershell/profile.ps1#L303-L304

**Comment by jetersen** [comment]
> that does imply you have a template for that segment, right?

Indeed, however the templateText with `len(s.templateText) > 0` as I understand would end up containing the username and ignoring the `defaultUser` all together.

**Comment by JanDeDobbeleer** [comment]
@jetersen that depends on m the template logic. Can you share the template you're using? In the tests there's a template that illustrates this behavior.

**Comment by jetersen** [comment]
My dotfiles link above contains my entire oh my posh config

**Comment by jetersen** [comment]
I see, I am not using a template.

However the default username is still shown 😅

**Comment by JanDeDobbeleer** [comment]
@jetersen my bad, didn't see there were two links. I'll validate this ASAP. In the meantime, using only the template should fix the issue. The last test added should have what you're looking for.

**Comment by jetersen** [comment]
@JanDeDobbeleer I found the bug, see #454

**Comment by Plasma** [comment]
I think there may be a subtle bug still, I'm on the release this supposedly is fixed in (`v3.123.0`) but on Windows I still see my name:

> Andrew@my-desktop | C:\example | develop 

Using any of the themes (in particular, trying `powerline`) I've tried editing its `powerline.omp.json` file to trigger the "Dont show name if its the default" but its still always appearing:

```json
{
    "type": "session",
    "style": "plain",
    "foreground": "#ffffff",
    "display_default": false
}
```

I've also tried setting system environment `POSH_SESSION_DEFAULT_USER` to `Andrew` (and `Andrew@my-desktop`) with no luck.

Updating the json to also have `default_user_name` to be `Andrew` also fails. Any ideas?

**Comment by JanDeDobbeleer** [comment]
@Plasma yes. That property needs to be in a `properties` object rather than at the segment root.

**Comment by eamodio** [comment]
I'm having the same issue on Windows on `v3.129.0`, I've also tried setting `POSH_SESSION_DEFAULT_USER` to `eric`, `Eric`, `Eric@my-pc-name`. I've also set the `default_user_name` below to all those values. And I always see that segment.

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "type": "prompt",
      "segments": [
        {
          "type": "session",
          "style": "diamond",
          "foreground": "#ffffff",
          "background": "#61AFEF",
          "leading_diamond": "",
          "trailing_diamond": "",
          "properties": {
            "default_user_name": "eric",
            "display_default": false
          }
        },
        {
          "type": "path",
          "style": "powerline",
          "foreground": "#e9d9f2",
          "background": "#7d16bf",
          "powerline_symbol": "",
          "properties": {
            "style": "full",
            "enable_hyperlink": false
          }
        },
        {
          "type": "poshgit",
          "style": "powerline",
          "foreground": "#e9d9f2",
          "background": "#4D057B",
          "powerline_symbol": ""
        }
      ]
    }
  ],
  "final_space": true
}
```

**Comment by eamodio** [comment]
@JanDeDobbeleer Any thoughts on why I'm seeing this: https://github.com/JanDeDobbeleer/oh-my-posh/issues/453#issuecomment-808963388? Thanks! 😄

**Comment by JanDeDobbeleer** [comment]
@eamodio sorry, missed that. Allow me to validate this evening.

**Comment by eamodio** [comment]
Awesome -- thank you!

**Comment by eamodio** [comment]
FYI, I also updated to 3.130.1 and see the same thing.

**Comment by JanDeDobbeleer** [comment]
@eamodio weird, for me this works perfectly on macOS, I even copied your settings so that's legit. Could it be your user name has spaces? I'll trim just to make sure but that's basically the only thing I can think off.

**Comment by eamodio** [comment]
Hrm, I ran `$env:UserName` in pwsh and it returns `Eric` without any leading or trailing spaces.
