### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ShlomiD83** [JanDeDobbeleer/oh-my-posh#6578]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### What happened?

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x129e3b3]

goroutine 1 [running]:
github.com/jandedobbeleer/oh-my-posh/src/config.(*Config).upgradeFeatures(0xc00031e160, {0x17290d8, 0xc00032a000})
        D:/a/oh-my-posh/oh-my-posh/src/config/config.go:193 +0xb3
github.com/jandedobbeleer/oh-my-posh/src/config.(*Config).Features(0xc00031e160, {0x17290d8, 0xc00032a000})
        D:/a/oh-my-posh/oh-my-posh/src/config/config.go:134 +0x3d9
github.com/jandedobbeleer/oh-my-posh/src/cli.runInit({0xc00010e160, 0x4})
        D:/a/oh-my-posh/oh-my-posh/src/cli/init.go:98 +0x234
github.com/jandedobbeleer/oh-my-posh/src/cli.createInitCmd.func1(0xc0001c6700?, {0xc0003000c0?, 0x4?, 0x152b544?})
        D:/a/oh-my-posh/oh-my-posh/src/cli/init.go:54 +0x2f
github.com/spf13/cobra.(*Command).execute(0xc0002ba308, {0xc000300090, 0x1, 0x1})
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1019 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x1d79860)
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148 +0x46f
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1071
github.com/jandedobbeleer/oh-my-posh/src/cli.Execute()
        D:/a/oh-my-posh/oh-my-posh/src/cli/root.go:94 +0x1a
main.main()
        D:/a/oh-my-posh/oh-my-posh/src/main.go:8 +0xf

this happens after the latest update, checked 2 machines.

### Theme

no theme or config.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x129e3b3]

goroutine 1 [running]:
github.com/jandedobbeleer/oh-my-posh/src/config.(*Config).upgradeFeatures(0xc00031e160, {0x17290d8, 0xc00032a000})
        D:/a/oh-my-posh/oh-my-posh/src/config/config.go:193 +0xb3
github.com/jandedobbeleer/oh-my-posh/src/config.(*Config).Features(0xc00031e160, {0x17290d8, 0xc00032a000})
        D:/a/oh-my-posh/oh-my-posh/src/config/config.go:134 +0x3d9
github.com/jandedobbeleer/oh-my-posh/src/cli.runInit({0xc00010e160, 0x4})
        D:/a/oh-my-posh/oh-my-posh/src/cli/init.go:98 +0x234
github.com/jandedobbeleer/oh-my-posh/src/cli.createInitCmd.func1(0xc0001c6700?, {0xc0003000c0?, 0x4?, 0x152b544?})
        D:/a/oh-my-posh/oh-my-posh/src/cli/init.go:54 +0x2f
github.com/spf13/cobra.(*Command).execute(0xc0002ba308, {0xc000300090, 0x1, 0x1})
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1019 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x1d79860)
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148 +0x46f
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1071
github.com/jandedobbeleer/oh-my-posh/src/cli.Execute()
        D:/a/oh-my-posh/oh-my-posh/src/cli/root.go:94 +0x1a
main.main()
        D:/a/oh-my-posh/oh-my-posh/src/main.go:8 +0xf
```

**Comment by JanDeDobbeleer** [comment]
@ShlomiD83 fixed in `26.14.1`

**Comment by ShlomiD83** [comment]
> [@ShlomiD83](https://github.com/ShlomiD83) fixed in `26.14.1`

<img width="577" height="162" alt="Image" src="https://github.com/user-attachments/assets/e2f19165-adbf-41c4-838b-e62c5ce8eb98" />

updated manually, but still seeing this.
not using any special config or theme.
`oh-my-posh init pwsh | Invoke-Expression`

**Comment by JanDeDobbeleer** [comment]
yes, on that one right now in #6579
