### ISSUE TITLE
auto upgrade doesn't work (stuck with 26.23.2, not updating automatically to a newer minor version, 26.23.3 or 26.23.4)

### ISSUE THREAD

**Issue by darkred** [JanDeDobbeleer/oh-my-posh#6775]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### What happened?

It's rather the same issue as #6245 .

I have OhMyPosh installed on Powershell (inside Windows Terminal).
It's stuck with 26.23.2, of 2 days ago. Since then there have been two newer minor versions (26.23.3 yesterday, 26.23.4 today) but auto upgrade hasn't updated to a newer version.

I have a "custom" theme, `ohmyposh_config.omp.json`, (in `C:\Users\<User>`) that is the out-of-the-box `jandedobbeleer.omp.json` with the addition of this setting:

```json
  "upgrade": {
    "notice": false,
    "auto": true,
    "interval": "24h",
    "source": "cdn"
  }
```

---

Note: to be exact, I'd noticed that I'd stuck with previous minor version 26.23.1. Then I (accidentally) ran the windows installer (install-x64.msi) of 26.23.1 on top of my installation, didn't make a difference. Then I did a `oh-my-posh cache clear` as suggested [here](https://github.com/JanDeDobbeleer/oh-my-posh/issues/6245#issuecomment-2722060708) and it updated to 26.23.2 .

I also tried opening `"%LocalAppData%\oh-my-posh\omp.cache"` as mentioned [here](https://github.com/JanDeDobbeleer/oh-my-posh/issues/6245#issuecomment-2735584889) but the file seems corrupted:

![Image](https://github.com/user-attachments/assets/3491c5a8-84b5-4dcf-86a5-73b9b37cfa72)

### Theme

ohmyposh_config.omp.json

<details>
 <summary>Click to expand:</summary>

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "segments": [
        {
          "background": "#c386f1",
          "foreground": "#ffffff",
          "leading_diamond": "\ue0b6",
          "style": "diamond",
          "template": " {{ .UserName }} ",
          "trailing_diamond": "\ue0b0",
          "type": "session"
        },
        {
          "background": "#ff479c",
          "foreground": "#ffffff",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "folder_separator_icon": " \ue0b1 ",
            "home_icon": "~",
            "style": "folder"
          },
          "style": "powerline",
          "template": " \uea83  {{ .Path }} ",
          "type": "path"
        },
        {
          "background": "#fffb38",
          "background_templates": [
            "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}",
            "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}",
            "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
            "{{ if gt .Behind 0 }}#B388FF{{ end }}"
          ],
          "foreground": "#193549",
          "leading_diamond": "\ue0b6",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "branch_template": "{{ trunc 25 .Branch }}",
            "fetch_status": true,
            "fetch_upstream_icon": true
          },
          "style": "powerline",
          "template": " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} ",
          "trailing_diamond": "\ue0b4",
          "type": "git"
        },
        {
          "background": "#6CA35E",
          "foreground": "#ffffff",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "fetch_version": true
          },
          "style": "powerline",
          "template": " \ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} ",
          "type": "node"
        },
        {
          "background": "#8ED1F7",
          "foreground": "#111111",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "fetch_version": true
          },
          "style": "powerline",
          "template": " \ue626 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} ",
          "type": "go"
        },
        {
          "background": "#4063D8",
          "foreground": "#111111",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "fetch_version": true
          },
          "style": "powerline",
          "template": " \ue624 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} ",
          "type": "julia"
        },
        {
          "background": "#FFDE57",
          "foreground": "#111111",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "display_mode": "files",
            "fetch_virtual_env": false
          },
          "style": "powerline",
          "template": " \ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} ",
          "type": "python"
        },
        {
          "background": "#AE1401",
          "foreground": "#ffffff",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "display_mode": "files",
            "fetch_version": true
          },
          "style": "powerline",
          "template": " \ue791 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} ",
          "type": "ruby"
        },
        {
          "background": "#FEAC19",
          "foreground": "#ffffff",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "display_mode": "files",
            "fetch_version": false
          },
          "style": "powerline",
          "template": " \uf0e7{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} ",
          "type": "azfunc"
        },
        {
          "background_templates": [
            "{{if contains \"default\" .Profile}}#FFA400{{end}}",
            "{{if contains \"jan\" .Profile}}#f1184c{{end}}"
          ],
          "foreground": "#ffffff",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "display_default": false
          },
          "style": "powerline",
          "template": " \ue7ad {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} ",
          "type": "aws"
        },
        {
          "background": "#ffff66",
          "foreground": "#111111",
          "powerline_symbol": "\ue0b0",
          "style": "powerline",
          "template": " \uf0ad ",
          "type": "root"
        },
        {
          "background": "#83769c",
          "foreground": "#ffffff",
          "properties": {
            "always_enabled": true
          },
          "style": "plain",
          "template": "<transparent>\ue0b0</> \ueba2 {{ .FormattedMs }}\u2800",
          "type": "executiontime"
        },
        {
          "background": "#00897b",
          "background_templates": [
            "{{ if gt .Code 0 }}#e91e63{{ end }}"
          ],
          "foreground": "#ffffff",
          "properties": {
            "always_enabled": true
          },
          "style": "diamond",
          "template": "<parentBackground>\ue0b0</> \ue23a ",
          "trailing_diamond": "\ue0b4",
          "type": "status"
        }
      ],
      "type": "prompt"
    },
    {
      "segments": [
        {
          "background": "#0077c2",
          "foreground": "#ffffff",
          "style": "plain",
          "template": "<#0077c2,transparent>\ue0b6</> \uf489 {{ .Name }} <transparent,#0077c2>\ue0b2</>",
          "type": "shell"
        },
        {
          "background": "#1BD760",
          "foreground": "#111111",
          "invert_powerline": true,
          "powerline_symbol": "\ue0b2",
          "properties": {
            "paused_icon": "\uf04c ",
            "playing_icon": "\uf04b "
          },
          "style": "powerline",
          "template": " \uf167 {{ .Icon }}{{ if ne .Status \"stopped\" }}{{ .Artist }} - {{ .Track }}{{ end }} ",
          "type": "ytm"
        },
        {
          "background": "#f36943",
          "background_templates": [
            "{{if eq \"Charging\" .State.String}}#40c4ff{{end}}",
            "{{if eq \"Discharging\" .State.String}}#ff5722{{end}}",
            "{{if eq \"Full\" .State.String}}#4caf50{{end}}"
          ],
          "foreground": "#ffffff",
          "invert_powerline": true,
          "powerline_symbol": "\ue0b2",
          "properties": {
            "charged_icon": "\ue22f ",
            "charging_icon": "\ue234 ",
            "discharging_icon": "\ue231 "
          },
          "style": "powerline",
          "template": " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}\uf295 ",
          "type": "battery"
        },
        {
          "background": "#2e9599",
          "foreground": "#111111",
          "invert_powerline": true,
          "leading_diamond": "\ue0b2",
          "style": "diamond",
          "template": " {{ .CurrentDate | date .Format }} ",
          "trailing_diamond": "\ue0b4",
          "type": "time"
        }
      ],
      "type": "rprompt"
    }
  ],
  "console_title_template": "{{ .Shell }} in {{ .Folder }}",
  "final_space": true,
  "version": 3,
  "upgrade": {
    "notice": false,
    "auto": true,
    "interval": "24h",
    "source": "cdn"
  }
}

```

</details>

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Version: 26.23.2

Shell: shell (7.5.3)

Prompt:

 Kostas    ~   0ms⠀                                                                      shell  00:03:24 

Segments:

ConsoleTitle(true)                         -   0 ms
Session(true)                              -   0 ms
Path(true)                                 -   4 ms
Git(false)                                 -   0 ms
Node(false)                                -   0 ms
Go(false)                                  -   0 ms
Julia(false)                               -   0 ms
Python(false)                              -   0 ms
Ruby(false)                                -   0 ms
Azfunc(false)                              -   0 ms
Aws(false)                                 -   1 ms
Root(false)                                -   1 ms
Executiontime(true)                        -   1 ms
Status(true)                               -   1 ms
Shell(true)                                -   0 ms
Ytm(false)                                 -   0 ms
Battery(false)                             -   2 ms
Time(true)                                 -   0 ms

Run duration: 28.9288ms

Cache path: C:\Users\Kostas\AppData\Local\oh-my-posh

Config path: C:\Users\Kostas\ohmyposh_config.omp.json

Logs:

[DEBUG] 00:03:24.671 debug.go:39 → logging enabled, raw mode: true
[DEBUG] 00:03:24.673 store.go:]:135 → cache key not found: prompt_count_cache in store: session
[TRACE] 00:03:24.673 store.go:](session prompt_count_cache) - 547.4µs
[TRACE] 00:03:24.673 terminal.go:setPromptCount() - 1.0626ms
[TRACE] 00:03:24.673 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.674 terminal.go:setPwd:102 → C:\Users\Kostas
[TRACE] 00:03:24.674 terminal.go:setPwd() - 616.7µs
[TRACE] 00:03:24.674 terminal.go:Init() - 1.6793ms
[TRACE] 00:03:24.674 init.go:SessionID() - 0s
[DEBUG] 00:03:24.674 path_windows.go:PackageFamilyName:44 → failed to get PackageFamilyName
[TRACE] 00:03:24.674 path_windows.go:PackageFamilyName() - 0s
[TRACE] 00:03:24.674 path.go:Path() - 0s
[DEBUG] 00:03:24.680 store.go:init:92 → loading cache key: prompt_count_cache in store: session
[DEBUG] 00:03:24.680 store.go:init:92 → loading cache key: CONFIG in store: session
[DEBUG] 00:03:24.680 store.go:init:92 → loading cache key: CONFIG_SOURCE in store: session
[TRACE] 00:03:24.680 store.go:init(session pwsh.61888019-c75f-4bb1-9594-571cf774e86a.omp.cache) - 6.6204ms
[TRACE] 00:03:24.680 path.go:Path() - 0s
[DEBUG] 00:03:24.685 store.go:init:92 → loading cache key: DSC_CONFIGURATION in store: device
[DEBUG] 00:03:24.685 store.go:init:92 → loading cache key: INITVERSIONCMD in store: device
[DEBUG] 00:03:24.685 store.go:init:92 → loading cache key: INITVERSIONPWSH in store: device
[DEBUG] 00:03:24.685 store.go:init:92 → loading cache key: upgrade_check in store: device
[DEBUG] 00:03:24.685 store.go:init:92 → loading cache key: DSC_SHELL in store: device
[TRACE] 00:03:24.685 store.go:init(device omp.cache) - 4.212ms
[DEBUG] 00:03:24.685 store.go:]:135 → cache key not found: reload in store: device
[TRACE] 00:03:24.685 store.go:](device reload) - 624.3µs
[DEBUG] 00:03:24.686 store.go:]:146 → found cache key: CONFIG in store: session
[TRACE] 00:03:24.686 store.go:](session CONFIG) - 1.2043ms
[TRACE] 00:03:24.687 gob.go:Restore() - 614µs
[TRACE] 00:03:24.687 gob.go:Get() - 1.8183ms
[TRACE] 00:03:24.687 terminal.go:Shell() - 0s
[TRACE] 00:03:24.688 terminal.go:Flags() - 0s
[DEBUG] 00:03:24.688 store.go:]:135 → cache key not found: template_cache in store: session
[TRACE] 00:03:24.688 store.go:](session template_cache) - 0s
[TRACE] 00:03:24.688 cache.go:restoreCache() - 0s
[TRACE] 00:03:24.688 terminal_windows.go:Root() - 521.7µs
[TRACE] 00:03:24.688 terminal.go:Shell() - 0s
[TRACE] 00:03:24.688 terminal.go:Flags() - 0s
[TRACE] 00:03:24.688 terminal.go:StatusCodes() - 0s
[TRACE] 00:03:24.688 terminal_windows.go:IsWsl() - 0s
[TRACE] 00:03:24.688 terminal.go:Flags() - 0s
[TRACE] 00:03:24.688 terminal.go:Flags() - 0s
[DEBUG] 00:03:24.688 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.688 terminal_windows.go:IsWsl() - 0s
[TRACE] 00:03:24.688 terminal.go:Flags() - 0s
[TRACE] 00:03:24.688 terminal.go:Flags() - 0s
[TRACE] 00:03:24.688 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.688 terminal.go:User:236 → Kostas
[TRACE] 00:03:24.688 terminal.go:User() - 0s
[DEBUG] 00:03:24.688 terminal.go:Host:253 → Kostas-PC
[TRACE] 00:03:24.688 terminal.go:Host() - 0s
[TRACE] 00:03:24.688 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.688 terminal.go:Getenv:64 → NO DATA
[TRACE] 00:03:24.688 terminal.go:Getenv(SHLVL) - 0s
[DEBUG] 00:03:24.689 writer.go:Init:107 → terminal program: Windows Terminal
[DEBUG] 00:03:24.689 writer.go:Init:108 → terminal shell: shell
[DEBUG] 00:03:24.689 terminal.go:Getenv:64 → NO DATA
[TRACE] 00:03:24.689 terminal.go:Getenv(OMP_CACHE_DISABLED) - 0s
[DEBUG] 00:03:24.689 store.go:]:135 → cache key not found: accent_color in store: device
[TRACE] 00:03:24.689 store.go:](device accent_color) - 0s
[DEBUG] 00:03:24.689 terminal_windows.go:WindowsRegistryKeyValue:198 → ColorizationColor(DWORD): 0xC40078D4
[TRACE] 00:03:24.689 terminal_windows.go:WindowsRegistryKeyValue(HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor) - 0s
[TRACE] 00:03:24.689 colors_windows.go:GetAccentColor() - 0s
[TRACE] 00:03:24.689 colors.go:SetAccentColor() - 0s
[TRACE] 00:03:24.689 terminal.go:Shell() - 0s
[DEBUG] 00:03:24.689 terminal.go:Getenv:64 → 7.5.3
[TRACE] 00:03:24.689 terminal.go:Getenv(POSH_SHELL_VERSION) - 0s
[DEBUG] 00:03:24.689 debug.go:PrintDebug:24 → segment: Title
[DEBUG] 00:03:24.689 text.go:patchTemplate:149 → {{ .Shell }} in {{ .Folder }}
[TRACE] 00:03:24.690 terminal.go:Flags() - 0s
[DEBUG] 00:03:24.690 terminal.go:Getenv:64 → 3
[TRACE] 00:03:24.690 terminal.go:Getenv(POSH_CURSOR_LINE) - 0s
[DEBUG] 00:03:24.690 terminal.go:Getenv:64 → 1
[TRACE] 00:03:24.690 terminal.go:Getenv(POSH_CURSOR_COLUMN) - 0s
[TRACE] 00:03:24.690 terminal.go:Flags() - 0s
[TRACE] 00:03:24.690 terminal.go:Flags() - 0s
[TRACE] 00:03:24.690 terminal.go:Flags() - 0s
[TRACE] 00:03:24.690 terminal.go:Flags() - 0s
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.690 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.690 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.690 segment.go:Execute:108 → segment: Node
[DEBUG] 00:03:24.690 segment.go:Execute:108 → segment: Path
[DEBUG] 00:03:24.690 store.go:]:135 → cache key not found: toggle_cache in store: session
[DEBUG] 00:03:24.690 store.go:]:135 → cache key not found: toggle_cache in store: session
[TRACE] 00:03:24.690 store.go:](session toggle_cache) - 0s
[DEBUG] 00:03:24.690 segment.go:isToggled:229 → no toggles found
[TRACE] 00:03:24.690 terminal.go:Flags() - 0s
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.690 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.690 segment.go:Execute:108 → segment: Git
[DEBUG] 00:03:24.690 store.go:]:135 → cache key not found: toggle_cache in store: session
[TRACE] 00:03:24.690 store.go:](session toggle_cache) - 0s
[DEBUG] 00:03:24.690 segment.go:isToggled:229 → no toggles found
[TRACE] 00:03:24.690 terminal.go:Flags() - 0s
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.690 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.690 segment.go:Execute:108 → segment: Session
[DEBUG] 00:03:24.690 store.go:]:135 → cache key not found: toggle_cache in store: session
[TRACE] 00:03:24.690 store.go:](session toggle_cache) - 0s
[DEBUG] 00:03:24.690 segment.go:isToggled:229 → no toggles found
[DEBUG] 00:03:24.690 properties.go:GetStringArray:70 → extensions: [*.js *.ts package.json .nvmrc pnpm-workspace.yaml .pnpmfile.cjs .vue]
[DEBUG] 00:03:24.690 properties.go:GetStringArray:70 → folders: []
[DEBUG] 00:03:24.690 properties.go:GetBool:40 → home_enabled: false
[DEBUG] 00:03:24.690 properties.go:GetBool:40 → display_cygpath: false
[TRACE] 00:03:24.690 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.690 terminal.go:ResolveSymlink:195 → C:\Users\Kostas
[TRACE] 00:03:24.690 terminal.go:ResolveSymlink(C:\Users\Kostas) - 547.6µs
[DEBUG] 00:03:24.690 terminal.go:Getenv:64 → NO DATA
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.690 terminal.go:Getenv(SSH_CONNECTION) - 0s
[DEBUG] 00:03:24.690 terminal.go:Getenv:64 → NO DATA
[TRACE] 00:03:24.690 terminal.go:Getenv(SSH_CLIENT) - 0s
[TRACE] 00:03:24.690 terminal.go:Flags() - 0s
[TRACE] 00:03:24.690 terminal.go:Flags() - 0s
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.690 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.690 segment.go:Execute:108 → segment: Go
[DEBUG] 00:03:24.690 store.go:]:135 → cache key not found: toggle_cache in store: session
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.690 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.690 segment.go:Execute:108 → segment: Julia
[TRACE] 00:03:24.690 store.go:](session toggle_cache) - 0s
[DEBUG] 00:03:24.690 store.go:]:135 → cache key not found: toggle_cache in store: session
[DEBUG] 00:03:24.690 segment.go:isToggled:229 → no toggles found
[TRACE] 00:03:24.690 store.go:](session toggle_cache) - 0s
[DEBUG] 00:03:24.690 segment.go:isToggled:229 → no toggles found
[DEBUG] 00:03:24.690 properties.go:GetStringArray:70 → extensions: [*.go go.mod go.sum go.work go.work.sum]
[DEBUG] 00:03:24.690 properties.go:GetStringArray:70 → folders: []
[DEBUG] 00:03:24.690 properties.go:GetBool:40 → home_enabled: false
[DEBUG] 00:03:24.690 properties.go:GetStringArray:70 → extensions: [*.jl]
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[DEBUG] 00:03:24.690 properties.go:GetStringArray:70 → folders: []
[DEBUG] 00:03:24.690 properties.go:GetBool:40 → home_enabled: false
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.690 terminal.go:Flags() - 0s
[TRACE] 00:03:24.690 terminal.go:Flags() - 0s
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.690 terminal.go:GOOS() - 0s
[TRACE] 00:03:24.690 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.690 segment.go:Execute:108 → segment: Ruby
[DEBUG] 00:03:24.690 segment.go:Execute:108 → segment: Python
[TRACE] 00:03:24.690 separator.go:Separator() - 0s
[DEBUG] 00:03:24.690 store.go:]:135 → cache key not found: toggle_cache in store: session
[DEBUG] 00:03:24.690 store.go:]:135 → cache key not found: toggle_cache in store: session
[TRACE] 00:03:24.690 store.go:](session toggle_cache) - 0s
[TRACE] 00:03:24.690 store.go:](session toggle_cache) - 0s
[TRACE] 00:03:24.690 terminal.go:Shell() - 0s
[DEBUG] 00:03:24.690 segment.go:isToggled:229 → no toggles found
[TRACE] 00:03:24.690 terminal.go:Shell() - 0s
[DEBUG] 00:03:24.690 properties.go:GetString:46 → display_mode: files
[DEBUG] 00:03:24.690 properties.go:GetStringArray:70 → extensions: [*.rb Rakefile Gemfile]
[DEBUG] 00:03:24.690 properties.go:GetStringArray:70 → extensions: [*.py *.ipynb pyproject.toml venv.bak]
[DEBUG] 00:03:24.690 properties.go:GetStringArray:70 → folders: []
[DEBUG] 00:03:24.690 properties.go:GetStringArray:70 → folders: [.venv venv virtualenv venv-win pyenv-win]
[TRACE] 00:03:24.690 terminal.go:HasParentFilePath(.git) - 547.6µs
[DEBUG] 00:03:24.690 properties.go:GetBool:40 → home_enabled: false
[DEBUG] 00:03:24.690 properties.go:GetBool:40 → home_enabled: false
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.690 terminal.go:Flags() - 0s
[TRACE] 00:03:24.690 terminal.go:Flags() - 0s
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.690 terminal.go:Flags() - 0s
[TRACE] 00:03:24.690 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.690 segment.go:Execute:108 → segment: Aws
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[DEBUG] 00:03:24.690 store.go:]:135 → cache key not found: toggle_cache in store: session
[TRACE] 00:03:24.690 terminal.go:GOOS() - 0s
[TRACE] 00:03:24.690 terminal.go:GOOS() - 0s
[TRACE] 00:03:24.690 store.go:](session toggle_cache) - 0s
[DEBUG] 00:03:24.690 segment.go:Execute:108 → segment: Root
[DEBUG] 00:03:24.690 segment.go:Execute:108 → segment: Azfunc
[DEBUG] 00:03:24.690 segment.go:isToggled:229 → no toggles found
[DEBUG] 00:03:24.690 store.go:]:135 → cache key not found: toggle_cache in store: session
[DEBUG] 00:03:24.690 store.go:]:135 → cache key not found: toggle_cache in store: session
[TRACE] 00:03:24.690 store.go:](session toggle_cache) - 0s
[TRACE] 00:03:24.690 store.go:](session toggle_cache) - 0s
[DEBUG] 00:03:24.690 segment.go:isToggled:229 → no toggles found
[DEBUG] 00:03:24.690 segment.go:isToggled:229 → no toggles found
[DEBUG] 00:03:24.690 properties.go:GetBool:40 → display_default: false
[DEBUG] 00:03:24.690 terminal.go:Getenv:64 → NO DATA
[TRACE] 00:03:24.690 terminal.go:Getenv(AWS_VAULT) - 0s
[DEBUG] 00:03:24.690 terminal.go:Getenv:64 → NO DATA
[TRACE] 00:03:24.690 terminal.go:Getenv(AWS_DEFAULT_PROFILE) - 0s
[DEBUG] 00:03:24.690 terminal.go:Getenv:64 → NO DATA
[DEBUG] 00:03:24.690 properties.go:GetStringArray:70 → extensions: [host.json local.settings.json function.json]
[TRACE] 00:03:24.690 terminal.go:Getenv(AWS_PROFILE) - 0s
[DEBUG] 00:03:24.690 properties.go:GetStringArray:70 → folders: []
[DEBUG] 00:03:24.690 terminal.go:Getenv:64 → NO DATA
[DEBUG] 00:03:24.690 properties.go:GetBool:40 → home_enabled: false
[TRACE] 00:03:24.690 terminal.go:Getenv(AWS_REGION) - 0s
[DEBUG] 00:03:24.690 terminal.go:Getenv:64 → NO DATA
[TRACE] 00:03:24.690 terminal.go:Getenv(AWS_DEFAULT_REGION) - 0s
[DEBUG] 00:03:24.690 terminal.go:Getenv:64 → NO DATA
[TRACE] 00:03:24.690 terminal.go:Getenv(AWS_CONFIG_FILE) - 0s
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[DEBUG] 00:03:24.690 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.690 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.690 segment.go:Execute:108 → segment: Executiontime
[DEBUG] 00:03:24.690 store.go:]:135 → cache key not found: toggle_cache in store: session
[TRACE] 00:03:24.690 store.go:](session toggle_cache) - 0s
[DEBUG] 00:03:24.690 segment.go:isToggled:229 → no toggles found
[ERROR] 00:03:24.691 terminal.go:FileContent:207 → open C:\Users\Kostas/.aws/config: The system cannot find the file specified.
[TRACE] 00:03:24.691 terminal.go:FileContent(C:\Users\Kostas/.aws/config) - 555.2µs
[DEBUG] 00:03:24.691 properties.go:GetBool:40 → always_enabled: true
[TRACE] 00:03:24.691 terminal.go:ExecutionTime() - 0s
[DEBUG] 00:03:24.691 properties.go:GetFloat64:52 → threshold: 500.000000
[TRACE] 00:03:24.692 terminal.go:Flags() - 0s
[DEBUG] 00:03:24.692 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.692 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.692 segment.go:Execute:108 → segment: Status
[DEBUG] 00:03:24.692 store.go:]:135 → cache key not found: toggle_cache in store: session
[TRACE] 00:03:24.692 store.go:](session toggle_cache) - 0s
[DEBUG] 00:03:24.692 segment.go:isToggled:229 → no toggles found
[TRACE] 00:03:24.692 terminal.go:StatusCodes() - 0s
[DEBUG] 00:03:24.692 properties.go:GetString:46 → status_template: {{ .Code }}
[TRACE] 00:03:24.692 terminal_windows.go:Root() - 0s
[DEBUG] 00:03:24.692 properties.go:GetString:46 → style: austin
[DEBUG] 00:03:24.692 text.go:patchTemplate:149 →  {{ .UserName }}
[DEBUG] 00:03:24.692 text.go:patchTemplate:149 → {{ .Code }}
[DEBUG] 00:03:24.693 properties.go:GetBool:40 → always_enabled: true
[TRACE] 00:03:24.693 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.693 properties.go:GetBool:40 → mapped_locations_enabled: true
[DEBUG] 00:03:24.693 properties.go:GetString:46 → windows_registry_icon: 
[DEBUG] 00:03:24.693 properties.go:GetString:46 → windows_registry_icon: 
[DEBUG] 00:03:24.693 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.693 separator.go:Separator() - 0s
[TRACE] 00:03:24.694 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.694 properties.go:GetString:46 → home_icon: ~
[DEBUG] 00:03:24.694 properties.go:GetKeyValueMap:64 → mapped_locations: map[]
[TRACE] 00:03:24.694 separator.go:Separator() - 0s
[TRACE] 00:03:24.694 terminal.go:GOOS() - 0s
[TRACE] 00:03:24.694 separator.go:Separator() - 0s
[TRACE] 00:03:24.694 terminal.go:GOOS() - 0s
[TRACE] 00:03:24.694 terminal.go:GOOS() - 0s
[TRACE] 00:03:24.694 terminal.go:GOOS() - 0s
[TRACE] 00:03:24.694 terminal.go:GOOS() - 0s
[TRACE] 00:03:24.694 terminal.go:Flags() - 0s
[DEBUG] 00:03:24.694 properties.go:GetStringArray:70 → cycle: []
[DEBUG] 00:03:24.694 properties.go:GetString:46 → folder_separator_template:
[DEBUG] 00:03:24.694 properties.go:GetString:46 → folder_separator_icon:  
[DEBUG] 00:03:24.694 properties.go:GetBool:40 → cycle_folder_separator: false
[DEBUG] 00:03:24.694 properties.go:GetString:46 → folder_format: %s
[DEBUG] 00:03:24.694 properties.go:GetString:46 → edge_format: %s
[DEBUG] 00:03:24.694 properties.go:GetString:46 → left_format: %s
[DEBUG] 00:03:24.694 properties.go:GetString:46 → right_format: %s
[TRACE] 00:03:24.694 terminal.go:Flags() - 0s
[TRACE] 00:03:24.694 terminal.go:GOOS() - 0s
[TRACE] 00:03:24.694 terminal.go:StackCount() - 0s
[DEBUG] 00:03:24.694 win32_windows.go:isWriteable:259 → not current user or in group
[DEBUG] 00:03:24.694 win32_windows.go:isWriteable:263 → current user is member of S-1-5-32-544
[DEBUG] 00:03:24.694 win32_windows.go:isWriteable:271 ↓
    WRITE_DAC
    WRITE_OWNER
    SYNCHRONIZE
    DELETE
    READ_CONTROL
[DEBUG] 00:03:24.694 win32_windows.go:isWriteable:273 → user has write access
[TRACE] 00:03:24.694 terminal_windows.go:DirIsWritable() - 553.1µs
[DEBUG] 00:03:24.694 text.go:patchTemplate:149 →    {{ .Data.Path }}
[DEBUG] 00:03:24.694 text.go:patchTemplate:149 → <transparent></>  {{ .Data.FormattedMs }}⠀
[DEBUG] 00:03:24.694 text.go:patchTemplate:149 → {{ if gt .Code 0 }}#e91e63{{ end }}
[DEBUG] 00:03:24.694 text.go:patchTemplate:149 → {{ if gt .Code 0 }}#e91e63{{ end }}
[TRACE] 00:03:24.694 terminal.go:Shell() - 0s
[TRACE] 00:03:24.694 terminal.go:Shell() - 0s
[TRACE] 00:03:24.694 terminal.go:Flags() - 0s
[DEBUG] 00:03:24.694 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.694 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.694 segment.go:Execute:108 → segment: Time
[DEBUG] 00:03:24.694 store.go:]:135 → cache key not found: toggle_cache in store: session
[TRACE] 00:03:24.694 store.go:](session toggle_cache) - 0s
[DEBUG] 00:03:24.694 segment.go:isToggled:229 → no toggles found
[TRACE] 00:03:24.694 terminal.go:Flags() - 0s
[TRACE] 00:03:24.694 terminal.go:Flags() - 0s
[DEBUG] 00:03:24.694 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.694 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.694 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.694 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.694 store.go:]:135 → cache key not found: toggle_cache in store: session
[DEBUG] 00:03:24.694 segment.go:Execute:108 → segment: Ytm
[TRACE] 00:03:24.694 store.go:](session toggle_cache) - 0s
[DEBUG] 00:03:24.694 store.go:]:135 → cache key not found: toggle_cache in store: session
[DEBUG] 00:03:24.694 segment.go:isToggled:229 → no toggles found
[TRACE] 00:03:24.694 store.go:](session toggle_cache) - 0s
[DEBUG] 00:03:24.694 properties.go:GetKeyValueMap:64 → mapped_shell_names: map[]
[DEBUG] 00:03:24.694 segment.go:isToggled:229 → no toggles found
[TRACE] 00:03:24.694 terminal.go:Shell() - 0s
[TRACE] 00:03:24.694 terminal.go:Flags() - 0s
[TRACE] 00:03:24.694 terminal.go:Flags() - 0s
[DEBUG] 00:03:24.694 home.go:12 → C:\Users\Kostas
[TRACE] 00:03:24.694 terminal.go:GOOS() - 0s
[DEBUG] 00:03:24.694 segment.go:Execute:108 → segment: Battery
[DEBUG] 00:03:24.694 text.go:patchTemplate:149 → <#0077c2,transparent></>  {{ .Data.Name }} <transparent,#0077c2></>
[DEBUG] 00:03:24.694 store.go:]:135 → cache key not found: toggle_cache in store: session
[TRACE] 00:03:24.694 store.go:](session toggle_cache) - 0s
[DEBUG] 00:03:24.694 segment.go:isToggled:229 → no toggles found
[TRACE] 00:03:24.694 terminal_windows.go:IsWsl() - 0s
[DEBUG] 00:03:24.695 properties.go:GetString:46 → time_format: 15:04:05
[DEBUG] 00:03:24.695 store.go:]:135 → cache key not found: ytmda_token in store: device
[TRACE] 00:03:24.695 store.go:](device ytmda_token) - 553µs
[ERROR] 00:03:24.695 ytm.go:Enabled:31 → YTMDA token not found, please authenticate using `oh-my-posh auth ytmda`
[ERROR] 00:03:24.696 terminal_windows_nix.go:BatteryState:16 → no battery
[TRACE] 00:03:24.696 terminal_windows_nix.go:BatteryState() - 2.1981ms
[DEBUG] 00:03:24.697 text.go:patchTemplate:149 →  {{ .Data.CurrentDate | date .Data.Format }}
[TRACE] 00:03:24.697 terminal.go:Shell() - 0s
[TRACE] 00:03:24.697 terminal.go:Shell() - 0s
[TRACE] 00:03:24.697 terminal.go:Flags() - 0s
[TRACE] 00:03:24.697 terminal.go:Shell() - 0s
[DEBUG] 00:03:24.697 terminal_windows.go:TerminalWidth:99 → terminal width: 120
[TRACE] 00:03:24.697 terminal_windows.go:TerminalWidth() - 0s
[TRACE] 00:03:24.697 path.go:Path() - 0s
```

**Comment by JanDeDobbeleer** [comment]
@darkred this was solved in 26.23.3 😅

**Comment by JanDeDobbeleer** [comment]
@darkred there's an issue, I'll fix this ASAP. Unfortunately I can't fix this retroactively.

**Comment by darkred** [comment]
@JanDeDobbeleer The issue is still not fixed, right? I tried to `upgrade --force` to version 26.23.5 or (later) to  26.23.8 but the issue still occurs.  

Two more things please: 
- Is there a command to see the next auto-update check is scheduled?
- Is my `omp.cache` is ok or corrupted? In previous version (25.1.1) I was able to see its content ([see](https://github.com/JanDeDobbeleer/oh-my-posh/issues/6245#issuecomment-2737698070)) (it was JSON), but now it appears to be binary (see screenshot in OP).

**Comment by JanDeDobbeleer** [comment]
@darkred the `omp.cache` is now binary so that's expected. I might be able to add a command that shows the contents though (somehow). There's no command to understand when it would upgrade (could be created).

On my machine, it does work, I've been successfully upgrading as of the version where I fixed the parsing. You can run `oh-my-posh cache clear` and start a new shell instance to see if it upgrades. If you add the `--trace` flag to the `init` command, it will also log if it enables auto-upgrade based on your config and settings. You can find the log at `oh-my-posh cache path`.

**Comment by darkred** [comment]
@JanDeDobbeleer Thanks for trying to help. Unfortunately, I'm convinced that the issue still exists: if I run `oh-my-posh cache clear` and open a new shell instance, then it upgrades ok. But, then auto-upgrade never works again (it's set to run every `24h`). I'm currently stuck with 26.24.1 for the last four days, even though two new versions have been released.

**Comment by JanDeDobbeleer** [comment]
@darkred aha! That's a path I didn't validate.
